import { observable } from 'mobx';

class EditorStateManager {
  static STAGE_TYPES = {
    VIDEO_CUSTOMISE: 'VIDEO_CUSTOMISE',
    AUDIO_CUSTOMISE: 'AUDIO_CUSTOMISE',
    CAPTION_CUSTOMISE: 'CAPTION_CUSTOMISE',
    PERSONALIZER:'PERSONALIZER_CUSTOMISE',
    NICHE_SCRIPT_CUSTOMISE:'NICHE_SCRIPT_CUSTOMISE',
    END_SCREENS_CUSTOMISE:'END_SCREENS_CUSTOMISE',
    IMAGE_LT_CUSTOMISE:'IMAGE_LT_CUSTOMISE',
    CALL_TO_ACTION:'CALL_TO_ACTION'
  };

  @observable
  stage = EditorStateManager.STAGE_TYPES.CAPTION_CUSTOMISE;

  @observable
  toolbar = null;
}

export default EditorStateManager;
